bamboo_project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from bamboo_project import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account_app.urls')),
    path('', include('index_app.urls')),
    path('', include('blog_app.urls')),
    path('', include('product_app.urls')),
    path('', include('about_us_app.urls')),
    path('', include('contact_us_app.urls')),
    path('', include('profile_app.urls')),
    path('', include('order_app.urls')),
    path('', include('dashboard_app.urls')),
    path('', include('chat_app.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
    path('comment/', include('comment.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "ایکات ملی"
admin.site.site_title = "ایکات ملی"
admin.site.index_title = "ایکات ملی"

blog_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('blog', views.BlogIndex.as_view(), name='blog'),
    path('blog-detail/<slug:slug>', views.BlogDetail.as_view(), name='blog_detail'),
    path('article-list', views.ArticleList.as_view(), name='article_list'),
    path('category-detail/<slug:slug>', views.CategoryDetail.as_view(), name='category_detail'),
    path('search-suggest-article', views.SearchSuggestArticle.as_view(), name='search_suggest_article'),
    path('search-result-article', views.SearchResultArticle.as_view(), name='search_result_article'),
]

profile_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('profile-desktop-menu/<str:phone>', views.profile_desktop_menu, name='profile_desktop_menu'),
    path('profile-mobile-menu/<str:phone>', views.profile_mobile_menu, name='profile_mobile_menu'),
    path('profile-mobile-header-menu/<str:phone>', views.profile_mobile_header_menu, name='profile_mobile_header_menu'),
    path('user-edit-profile/<str:phone>', views.UserEditProfile.as_view(), name='user_edit_profile'),
    path('user-change-password/<str:phone>', views.UserChangePassword.as_view(), name='user_change_password'),
    path('user-profile-dashborad/<str:phone>', views.UserProfileDashboard.as_view(), name='user_profile_dashboard'),
    path('user-profile-favorites/<str:phone>', views.UserProfileFavorite.as_view(), name='user_profile_favorites'),
    path('user-profile-orders/<str:phone>', views.UserProfileOrders.as_view(), name='user_profile_orders'),
    path('user-profile-order-detail/<str:unique_id>', views.UserProfileOrderDetail.as_view(),
         name='user_profile_order_detail'),
    path('user-profile-order-referral/<str:unique_id>', views.ReferralOrder.as_view(),
         name='user_profile_order_referral'),
    path('user-profile-notifications/<str:phone>', views.UserProfileNotification.as_view(),
         name='user_profile_notifications'),
    path('user-profile-prices/<str:phone>', views.UseGetPrize.as_view(),
         name='user_profile_prizes'),
    path('user-profile-address/<str:phone>', views.UserProfileAddress.as_view(), name='user_profile_address'),
    path('user-profile-add-address/<str:phone>', views.AddAddress.as_view(), name='user_profile_add_address'),
    path('user-profile-delete-address/<int:id>', views.DeleteAddress.as_view(), name='user_profile_delete_address'),
]

profile_app/models.py
import jdatetime
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django_jalali.db import models as jmodels

from account_app.models import User


class Notification(models.Model):
    title = models.CharField(max_length=200, verbose_name="عنوان")
    description = models.TextField(verbose_name='توضیحات', null=True, blank=True)
    url = models.URLField(verbose_name='لینک جزییات', null=True, blank=True)
    user = models.ManyToManyField(User, null=True, blank=True, verbose_name='انتخاب کاربران')
    remove_date = jmodels.jDateTimeField(null=True, blank=True, verbose_name='زمان حذف')
    created_at = jmodels.jDateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')
    updated_at = jmodels.jDateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'اعلان'
        verbose_name_plural = 'اعلانات'

    def remove(self):
        now = jdatetime.datetime.now()
        if self.remove_date:
            if self.remove_date < now:
                self.delete()
        else:
            if self.created_at + jdatetime.timedelta(days=14) < now:
                self.delete()

    def get_created_at(self):
        date = self.created_at.date()
        persian_months = ['فرودین', 'اردیبهشت', 'خرداد', 'تیر', 'مرداد', 'شهریور', 'مهر', 'آبان', 'آذر', 'دی', 'بهمن',
                          'اسفند']
        return f'{date.day} / {persian_months[date.month - 1]} / {date.year}'


class Address(models.Model):
    user = models.ForeignKey(User, verbose_name='کاربر', on_delete=models.CASCADE)
    address = models.TextField(verbose_name='نشانی ارسال')
    city = models.CharField(max_length=100, verbose_name='شهر')
    state = models.CharField(max_length=100, verbose_name='استان')
    plaque = models.CharField(max_length=10, verbose_name='پلاک')
    unit = models.CharField(max_length=10, verbose_name='واحد', null=True, blank=True)
    postal_code = models.CharField(max_length=10, verbose_name='کد پستی')

    def __str__(self):
        return self.user.phone

    class Meta:
        verbose_name = 'آدرس'
        verbose_name_plural = 'آدرس ها'


class Prize(models.Model):
    amount = models.PositiveIntegerField(verbose_name='مقدار جایزه')
    discount = models.ForeignKey('order_app.FactorDiscount', on_delete=models.CASCADE, verbose_name='کد تخفیف')

    def __str__(self):
        return self.discount.code

    class Meta:
        verbose_name = 'جایزه'
        verbose_name_plural = 'جایزه ها'


@receiver(post_save, sender=Prize)
def product_attribute_create(sender, instance, created, **kwargs):
    if created:
        if instance.discount.user.count() <= 0:
            instance.delete()

profile_app/forms.py
from account_app.models import User
from django import forms

from profile_app.models import Address


class UserDataForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['phone', 'fullname', 'email', 'national_code', ]


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['birthdate', ]


class AddAddressForm(forms.ModelForm):
    class Meta:
        model = Address
        exclude = ['user', ]

profile_app/views.py
import jdatetime
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.utils.decorators import method_decorator
from django.views import View
from django_ratelimit.decorators import ratelimit

from account_app.models import User
from order_app.models import Order, OrderReferral, FactorDiscount
from product_app.models import Product
from profile_app.forms import UserEditForm, UserDataForm, AddAddressForm
from django.http import HttpResponseForbidden

from profile_app.functions import remove_notif
from profile_app.models import Notification, Address, Prize


def profile_desktop_menu(request, phone):
    user = get_object_or_404(User, phone=phone)
    return render(request, 'profile_includes/desktop_menu.html',
                  {"user": user})


def profile_mobile_menu(request, phone):
    user = get_object_or_404(User, phone=phone)
    return render(request, 'profile_includes/mobile_menu.html',
                  {"user": user})


def profile_mobile_header_menu(request, phone):
    user = get_object_or_404(User, phone=phone)
    return render(request, 'profile_includes/mobile_header_menu.html',
                  {"user": user})


class UserProfileDashboard(View):
    profile_dashboard = {}

    # @method_decorator(ratelimit(key='user_or_ip', rate='20/m'))
    @method_decorator(login_required, name='dispatch', )
    def get(self, request, phone):
        user = get_object_or_404(User, phone=phone)
        if request.user == user or request.user.is_admin:
            return render(request, 'profiles_app/profile-dashboard.html', {'user': user})
        else:
            return HttpResponseForbidden()


class UserProfileFavorite(View):
    GET_profile_fav = {}

    @method_decorator(ratelimit(key='user_or_ip', rate='20/m'))
    @method_decorator(login_required, name='dispatch', )
    def get(self, request, phone):
        user = get_object_or_404(User, phone=phone)
        if request.user == user or request.user.is_admin:
            return render(request, 'profiles_app/profile-favorite.html', {'user': user})
        else:
            return HttpResponseForbidden()

    def post(self, request, phone):
        if request.user.is_authenticated:
            user = get_object_or_404(User, phone=phone)
            slug = request.POST.get('slug')
            product = get_object_or_404(Product, slug=slug)
            if request.user == user or request.user.is_admin:
                product.favorites.remove(user)
                return redirect('user_profile_favorites', phone=phone)
            else:
                return HttpResponseForbidden()
        else:
            return redirect('user_login')


class UserProfileOrders(View):
    GET_profile_order = {}

    @method_decorator(ratelimit(key='user_or_ip', rate='20/m'))
    @method_decorator(login_required, name='dispatch', )
    def get(self, request, phone):
        user = get_object_or_404(User, phone=phone)
        if request.user == user or request.user.is_admin:
            orders = user.orders.order_by('-created_at')
            page_num = request.GET.get('page', 1)
            paginator = Paginator(orders, 10)
            try:
                page_obj = paginator.page(page_num)
            except PageNotAnInteger:
                page_obj = paginator.page(1)
            except EmptyPage:
                page_obj = paginator.page(paginator.num_pages)
            return render(request, 'profiles_app/profile-orders.html', {'user': user, 'orders': page_obj})
        else:
            return HttpResponseForbidden()


class ReferralOrder(View):
    GET_profile_referral = {}

    @method_decorator(ratelimit(key='user_or_ip', rate='20/m'))
    @method_decorator(login_required, name='dispatch', )
    def get(self, request, unique_id):
        order = get_object_or_404(Order, unique_id=unique_id)
        if order.user == request.user or request.user.is_admin:
            if order.is_valid_for_referral():
                return render(request, 'profiles_app/profile-referral-order.html', {'order': order})
            else:
                messages.error(request, 'از سفارش شما 24 ساعت گذشته است')
                return redirect('user_profile_orders', order.user.phone)
        else:
            return HttpResponseForbidden()

    @method_decorator(login_required, name='dispatch', )
    def post(self, request, unique_id):
        order = get_object_or_404(Order, unique_id=unique_id)
        if order.user == request.user or request.user.is_admin:
            if not OrderReferral.objects.filter(order=order).exists():
                if order.is_valid_for_referral():
                    reason = request.POST.get('reason')
                    if reason:
                        image = request.FILES.get('image')
                        if image:
                            OrderReferral.objects.create(order=order, reason=reason, image=image)
                            messages.success(request,
                                             'درخواست شما با موفقیت ثبت شد، در اسرع وقت با شما تماس گرفته خواهد شد')
                            return redirect('user_profile_orders', order.user.phone)
                        else:
                            OrderReferral.objects.create(order=order, reason=reason)
                            messages.success(request,
                                             'درخواست شما با موفقیت ثبت شد، در اسرع وقت با شما تماس گرفته خواهد شد')
                            return redirect('user_profile_orders', order.user.phone)
                    else:
                        messages.error(request, 'لطفا دلیل مرجوع کردن را بنویسید')
                        return redirect('user_profile_order_referral', order.unique_id)
                else:
                    messages.error(request, 'از سفارش شما 24 ساعت گذشته است')
                    return redirect('user_profile_orders', order.user.phone)
            else:
                messages.error(request, 'درخواست شما برای این سفارش ثبت شده است')
                return redirect('user_profile_orders', order.user.phone)
        else:
            return HttpResponseForbidden()


class UserProfileOrderDetail(View):
    GET_profile_order_detail = {}

    @method_decorator(ratelimit(key='user_or_ip', rate='20/m'))
    @method_decorator(login_required, name='dispatch', )
    def get(self, request, unique_id):
        order = get_object_or_404(Order, unique_id=unique_id)
        if request.user == order.user or request.user.is_admin:
            return render(request, 'profiles_app/profile-orders-detail.html', {'order': order})
        else:
            return HttpResponseForbidden()


class UserProfileNotification(View):
    GET_profile_notif = {}

    @method_decorator(ratelimit(key='user_or_ip', rate='20/m'))
    @method_decorator(login_required, name='dispatch', )
    def get(self, request, phone):
        user = get_object_or_404(User, phone=phone)
        if request.user == user or request.user.is_admin:
            notifications = Notification.objects.filter(Q(user=user) | Q(user=None)).order_by('-created_at')
            remove_notif(notifications)
            page_num = request.GET.get('page', 1)
            paginator = Paginator(notifications, 5)
            try:
                page_obj = paginator.page(page_num)
            except PageNotAnInteger:
                page_obj = paginator.page(1)
            except EmptyPage:
                page_obj = paginator.page(paginator.num_pages)
            return render(request, 'profiles_app/profile-notification.html',
                          {'user': user, 'notifications': page_obj})
        else:
            return HttpResponseForbidden()


class UserProfileAddress(View):
    GET_profile_address = {}

    @method_decorator(ratelimit(key='user_or_ip', rate='20/m'))
    @method_decorator(login_required, name='dispatch', )
    def get(self, request, phone):
        user = get_object_or_404(User, phone=phone)
        if request.user == user or request.user.is_admin:
            form = AddAddressForm()
            return render(request, 'profiles_app/profile-address.html', {'user': user, 'form': form})
        else:
            return HttpResponseForbidden()

    @method_decorator(login_required, name='dispatch', )
    def post(self, request, phone):
        user = get_object_or_404(User, phone=phone)
        if request.user == user or request.user.is_admin:
            address_id = request.POST.get('address_id')
            if address_id:
                address = get_object_or_404(Address, id=address_id)
                if user == address.user or request.user.is_admin:
                    address.address = request.POST.get('old_address', address.address)
                    address.city = request.POST.get('city', address.city)
                    address.state = request.POST.get('state', address.state)
                    address.plaque = request.POST.get('plaque', address.plaque)
                    address.unit = request.POST.get('unit', address.unit)
                    address.postal_code = request.POST.get('postal_code', address.postal_code)
                    address.save()
                    return render(request, 'profiles_app/profile-address.html', {'user': user})
                else:
                    return HttpResponseForbidden()
            else:
                return render(request, 'profiles_app/profile-address.html', {'user': user})
        else:
            return HttpResponseForbidden()


class AddAddress(View):
    @method_decorator(login_required, name='dispatch', )
    def post(self, request, phone):
        user = get_object_or_404(User, phone=phone)
        if request.user == user or request.user.is_admin:
            if user.address_set.count() < 5:
                form = AddAddressForm(data=request.POST)

profile_app/templates/profiles_app/profile-dashboard.html
{% load static %}
{% load render_partial %}
{% load custom_filters %}
<!doctype html>
<html dir="rtl" lang="fa">
<head>
    <meta charset="UTF-8"/>
    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
    <title>پیشخوان</title>

    <link href="{% static 'index_app' %}/css/fonts.css" rel="stylesheet"/>
    <link href="{% static 'index_app' %}/css/dependencies/swiper.min.css" rel="stylesheet"/>
    <link href="{% static 'index_app' %}/css/app.css" rel="stylesheet"/>

    <script defer src="{% static 'index_app' %}/scripts/dependencies/flowbite.min.js"></script>
    <script defer src="{% static 'index_app' %}/scripts/dependencies/swiper.min.js"></script>

    <script defer src="{% static 'index_app' %}/scripts/app.js"></script>

    <script>
        // Set Theme from Localstorage at site load
        document.documentElement.classList.toggle(
            "dark",
            localStorage.getItem("theme") === "dark",
        );
    </script>
</head>

<body>
{% include 'includes/header.html' %}
<main class="flex-grow bg-gray-100 pb-14 pt-36 dark:bg-black xs:pt-36">
    <div class="container">
        <div class="grid grid-cols-12 gap-4">
            <!-- sidebar -->
            <div class="col-span-12 lg:col-span-3">
                {% with phone=user.phone %}
                    {% render_partial 'profile_app.views.profile_desktop_menu' phone=phone %}
                {% endwith %}
                {% include 'profile_includes/mobile_header_menu.html' %}
            </div>

            <!-- content -->
            <div class="col-span-12 lg:col-span-9">
                <div class="rounded-lg bg-white p-5 shadow-base dark:bg-zinc-900">
                    <!-- Title -->
                    <h1
                            class="relative mb-16 w-fit text-xl font-medium text-zinc-700 dark:text-white"
                    >
                        پیشخوان
                        <span
                                class="absolute right-0 top-10 h-[3px] w-full rounded-full bg-emerald-500 dark:bg-emerald-400"
                        >
                                      </span>
                    </h1>
                    <div class="mb-8">
                        <h2
                                class="mb-8 flex items-center gap-x-4 text-lg text-zinc-600 dark:text-zinc-300"
                        >
                                        <span
                                                class="h-2 w-2 rounded-full bg-emerald-500 dark:bg-emerald-400"
                                        ></span>
                            حساب کاربری
                        </h2>
                        <div class="grid grid-cols-2 gap-4 md:gap-6 xl:grid-cols-4">
                            <a
                                    href="{% url 'user_edit_profile' user.phone %}"
                                    class="flex flex-col items-center gap-4 rounded-base bg-sky-500 p-2 dark:bg-sky-600 md:flex-row"
                            >
                                <div
                                        class="relative rounded-base bg-sky-600/50 p-2 dark:bg-sky-500/50"
                                >
                                    <svg class="h-8 w-8 text-white">
                                        <use xlink:href="#user-setting"/>
                                    </svg>
                                </div>

                                <div class="text-sm font-medium text-white md:text-base">
                                    تکمیل مشخصات
                                </div>
                            </a>
                            <a
                                    href="{% url 'user_profile_favorites' user.phone %}"
                                    class="flex flex-col items-center gap-4 rounded-base bg-rose-500 p-2 dark:bg-rose-600 md:flex-row"
                            >
                                <div
                                        class="relative rounded-base bg-rose-600/50 p-2 dark:bg-rose-500/50"
                                >
                                    <svg class="h-8 w-8 text-white">
                                        <use xlink:href="#heart"/>
                                    </svg>
                                    <span
                                            class="absolute -right-1 -top-1 flex h-6 w-6 items-center justify-center rounded-full bg-rose-600 text-sm font-medium text-white dark:bg-rose-500 md:hidden"
                                    >
                                              {{ user.product_fav.count }}
                                            </span>
                                </div>

                                <div
                                        class="flex items-center gap-x-2 text-sm font-medium text-white md:text-base"
                                >
                                    <span class="hidden md:block">{{ user.product_fav.count }}</span> علاقه مندی
                                </div>
                            </a>
                            <a
                                    href="{% url 'user_profile_notifications' user.phone %}"
                                    class="flex flex-col items-center gap-4 rounded-base bg-emerald-500 p-2 dark:bg-emerald-600 md:flex-row"
                            >
                                <div
                                        class="relative rounded-base bg-emerald-600/50 p-2 dark:bg-emerald-500/50"
                                >
                                    <svg class="h-8 w-8 text-white">
                                        <use xlink:href="#notification"/>
                                    </svg>
                                    <span
                                            class="absolute -right-1 -top-1 flex h-6 w-6 items-center justify-center rounded-full bg-emerald-600 text-sm font-medium text-white dark:bg-emerald-500 md:hidden"
                                    >
                                              {{ user.notification_set.count }}
                                            </span>
                                </div>

                                <div
                                        class="flex items-center gap-x-2 text-sm font-medium text-white md:text-base"
                                >
                                    <span class="hidden md:block">{{ user.notification_set.count }}</span> اعلان
                                </div>
                            </a>
                        </div>
                    </div>

                    <div class="mb-8">
                        <div
                                class="mb-8 flex flex-wrap items-center justify-between gap-4"
                        >
                            <h3
                                    class="flex items-center gap-x-4 text-lg text-zinc-600 dark:text-zinc-300"
                            >
                                          <span
                                                  class="h-2 w-2 rounded-full bg-emerald-500 dark:bg-emerald-400"
                                          ></span>
                                وضعیت سفارش های شما
                            </h3>
                            <a
                                    class="btn-primary-nobg text-base"
                                    href="{% url 'user_profile_orders' user.phone %}"
                            >
                                مشاهده همه
                                <span>
                                            <svg class="h-5 w-5 lg:h-6 lg:w-6">
                                              <use xlink:href="#chevron-left"></use>
                                            </svg>
                                          </span>
                            </a>
                        </div>

                        <div class="grid grid-cols-2 gap-4 md:gap-6 xl:grid-cols-4">
                            <div
                                    class="flex flex-col items-center gap-4 rounded-base bg-sky-500 p-2 dark:bg-sky-600 md:flex-row"
                            >
                                <div
                                        class="relative rounded-base bg-sky-600/50 p-2 dark:bg-sky-500/50"
                                >
                                    <svg class="h-10 w-10 text-white">
                                        <use xlink:href="#order-current"/>
                                    </svg>
                                    <span
                                            class="absolute -right-1 -top-1 flex h-6 w-6 items-center justify-center rounded-full bg-sky-600 text-sm font-medium text-white dark:bg-sky-500 md:hidden"
                                    >
                                              {{ user.orders.all|get_active_orders }}
                                            </span>
                                </div>
                                <div class="flex flex-col gap-y-1">
                                    <div class="hidden font-medium text-white md:block">
                                        {{ user.orders.all|get_active_orders }} سفارش
                                    </div>
                                    <div class="text-white">فعلی</div>
                                </div>
                            </div>

                            <!-- item -->
                            <div
                                    class="flex flex-col items-center gap-4 rounded-base bg-emerald-500 p-2 dark:bg-emerald-600 md:flex-row"
                            >
                                <div
                                        class="relative rounded-base bg-emerald-600/50 p-2 dark:bg-emerald-500/50"
                                >
                                    <svg class="h-10 w-10 text-white">
                                        <use xlink:href="#order-delivered"/>
                                    </svg>
                                    <span
                                            class="absolute -right-1 -top-1 flex h-6 w-6 items-center justify-center rounded-full bg-emerald-600 text-sm font-medium text-white dark:bg-emerald-500 md:hidden"
                                    >
                                              {{ user.orders.all|get_send_orders }}
                                            </span>
                                </div>
                                <div class="flex flex-col gap-y-1">
                                    <div class="hidden font-medium text-white md:block">
                                        {{ user.orders.all|get_send_orders }} سفارش
                                    </div>
                                    <div class="text-white">ارسال شده</div>
                                </div>
                            </div>

                            <!-- item -->
                            <div
                                    class="flex flex-col items-center gap-4 rounded-base bg-red-500 p-2 dark:bg-red-400 md:flex-row"
                            >
                                <div
                                        class="relative rounded-base bg-red-400/50 p-2 dark:bg-red-500/50"
                                >
                                    <svg class="h-10 w-10 text-white">
                                        <use xlink:href="#order-canceled"/>
                                    </svg>
                                    <span
                                            class="absolute -right-1 -top-1 flex h-6 w-6 items-center justify-center rounded-full bg-red-400 text-sm font-medium text-white dark:bg-red-500 md:hidden"
                                    >
                                              {{ user.orders.all|get_referral_orders }}
                                            </span>
                                </div>
                                <div class="flex flex-col gap-y-1">
                                    <div class="hidden font-medium text-white md:block">
                                        {{ user.orders.all|get_referral_orders }} سفارش
                                    </div>
                                    <div class="text-white">مرجوع شده</div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% include 'profile_includes/mobile_menu.html' %}
</div>
</body>
</html>